name: Python Linting and Formatting

on:
  push:
    paths:
      - '**.py'
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
    paths:
      - '**.py'

jobs:
  Ruff:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: Install Ruff
        run: |
          python -m pip install ruff
      - name: Version
        run: |
          ruff --version
      - name: Run Ruff code check
        run: |
          ruff check
      - name: Run Ruff format check
        run: |
          ruff format --check --diff
